name: PGCN
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - pyarrow
  - numpy
  - networkx
  - tqdm
  - pydantic
  - rich
  - pytest
  - pip
  - pip:
      - caveclient
      - neuprint-python
      - tenacity
      - streamlit
      - scikit-learn
